# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.12

#Fabric api
fabric_version=0.119.6+1.21.5

# Third-party Properties
cloth_version=18.0.145
modmenu_version=14.0.0-rc.2

# Mod Properties
maven_group = squeek.appleskin
archives_base_name = appleskin-fabric
mod_version = 3.0.6
