# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

#Fabric api
fabric_api_version=0.160.6+26.3

# Third-party Properties
cloth_version=26.1.154
modmenu_version=21.0.0-beta.1
rei_version=26.2.821
jei_version=30.32.0.221

# Mod Properties
maven_group = squeek.appleskin
archives_base_name = appleskin-fabric
mod_version = 3.0.10
