# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
yarn_mappings=1.21.9+build.1
loader_version=0.17.2

#Fabric api
fabric_version=0.134.0+1.21.9

# Third-party Properties
cloth_version=20.0.148
modmenu_version=16.0.0-rc.1

# Mod Properties
maven_group = squeek.appleskin
archives_base_name = appleskin-fabric
mod_version = 3.0.7
